[package]
name = "stemcraft-core"
version.workspace = true
edition.workspace = true

[dependencies]
demucs-core.workspace = true
burn.workspace = true
cubecl.workspace = true
anyhow = "1.0.104"
pollster = "1.0.1"
realfft = "3.5.0"
hound = "3.5.1"
symphonia = { version = "0.5", features = ["mp3", "aac", "isomp4", "aiff", "alac"] }
ureq = "3.4.2"
dirs = "7.0.0"
flacenc = "0.5.1"
rubato = "5.0.0"

[dev-dependencies]
tempfile = "3.27.0"
